In [9]:
import pandas as pd

# Read CSV file into a DataFrame
df = pd.read_csv('defunciones_covid19_2020_2024.csv', sep=";")

df

AÑO   FECHA_DEF SEXO_NOMBRE  EDAD_TIPO  EDAD_CANT  COD_COMUNA  \
0      2020  2020-12-31       Mujer          1         99        7101   
1      2020  2020-03-20      Hombre          1         64       13102   
2      2020  2020-03-21       Mujer          1         82       13128   
3      2020  2020-03-25      Hombre          1         82        8101   
4      2020  2020-03-26      Hombre          1         79        8112   
...     ...         ...         ...        ...        ...         ...   
58308  2024  2024-10-23       Mujer          1         81        5109   
58309  2024  2024-10-21       Mujer          1         79        5701   
58310  2024  2024-11-05       Mujer          1         87       12101   
58311  2024  2024-11-08      Hombre          1         75        7101   
58312  2024  2024-11-07      Hombre          1        100        8108   

                    COMUNA                            NOMBRE_REGION DIAG1  \
0                    Talca                                Del Maule  U071   
1                Cerrillos                Metropolitana de Santiago  U071   
2                    Renca                Metropolitana de Santiago  U071   
3               Concepción                               Del Bíobío  U071   
4                  Hualpén                               Del Bíobío  U071   
...                    ...                                      ...   ...   
58308         Viña del Mar                            De Valparaíso  U099   
58309           San Felipe                            De Valparaíso  U099   
58310         Punta Arenas  De Magallanes y de La Antártica Chilena  U099   
58311                Talca                                Del Maule  U099   
58312  San Pedro de la Paz                               Del Bíobío  U099   

      CAPITULO_DIAG1  ... DIAG2 CAPITULO_DIAG2 GLOSA_CAPITULO_DIAG2  \
0            U00-U99  ...   NaN            NaN                  NaN   
1            U00-U99  ...   NaN            NaN                  NaN   
2            U00-U99  ...   NaN            NaN                  NaN   
3            U00-U99  ...   NaN            NaN                  NaN   
4            U00-U99  ...   NaN            NaN                  NaN   
...              ...  ...   ...            ...                  ...   
58308        U00-U99  ...   NaN            NaN                  NaN   
58309        U00-U99  ...   NaN            NaN                  NaN   
58310        U00-U99  ...   NaN            NaN                  NaN   
58311        U00-U99  ...   NaN            NaN                  NaN   
58312        U00-U99  ...   NaN            NaN                  NaN   

      CODIGO_GRUPO_DIAG2 GLOSA_GRUPO_DIAG2 CODIGO_CATEGORIA_DIAG2  \
0                    NaN               NaN                    NaN   
1                    NaN               NaN                    NaN   
2                    NaN               NaN                    NaN   
3                    NaN               NaN                    NaN   
4                    NaN               NaN                    NaN   
...                  ...               ...                    ...   
58308                NaN               NaN                    NaN   
58309                NaN               NaN                    NaN   
58310                NaN               NaN                    NaN   
58311                NaN               NaN                    NaN   
58312                NaN               NaN                    NaN   

      GLOSA_CATEGORIA_DIAG2 CODIGO_SUBCATEGORIA_DIAG2  \
0                       NaN                       NaN   
1                       NaN                       NaN   
2                       NaN                       NaN   
3                       NaN                       NaN   
4                       NaN                       NaN   
...                     ...                       ...   
58308                   NaN                       NaN   
58309                   NaN                       NaN   
58310      

In [12]:
len(df.columns.tolist())

27

In [16]:
df["EDAD_TIPO"].unique()

array([1, 2, 3])

In [29]:
l = df[df["EDAD_TIPO"] == 2]["EDAD_CANT"].unique()
l.sort()
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
l = df[df["EDAD_TIPO"] == 1]["EDAD_CANT"].unique()
l.sort()
l

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 113, 126])

In [31]:
l = df[df["EDAD_TIPO"] == 3]["EDAD_CANT"].unique()
l.sort()
l

array([28, 30])

In [40]:
df["FECHA_DEF"][0]

Timestamp('2020-12-31 00:00:00')

In [44]:
diag_columns = [x for x in df.columns.unique().tolist() if "DIAG" in x]

for diag_column in diag_columns:
    print(diag_column)
    print(df[diag_column].unique())

DIAG1
['U071' 'U072' 'U099']
CAPITULO_DIAG1
['U00-U99']
GLOSA_CAPITULO_DIAG1
['Códigos para propósitos especiales']
CODIGO_GRUPO_DIAG1
['U00-U49']
GLOSA_GRUPO_DIAG1
['Asignación provisoria de nuevas afecciones de etiología incierta']
CODIGO_CATEGORIA_DIAG1
['U07' 'U09']
GLOSA_CATEGORIA_DIAG1
['Uso emergente de U07' 'Condición de salud posterior a COVID-19']
CODIGO_SUBCATEGORIA_DIAG1
['U071' 'U072' 'U099']
GLOSA_SUBCATEGORIA_DIAG1
['COVID-19 virus identificado' 'COVID-19 virus no identificado'
 'Condición de salud posterior a COVID-19 no especificada']
DIAG2
[nan '    ']
CAPITULO_DIAG2
[nan]
GLOSA_CAPITULO_DIAG2
[nan]
CODIGO_GRUPO_DIAG2
[nan]
GLOSA_GRUPO_DIAG2
[nan]
CODIGO_CATEGORIA_DIAG2
[nan]
GLOSA_CATEGORIA_DIAG2
[nan]
CODIGO_SUBCATEGORIA_DIAG2
[nan]
GLOSA_SUBCATEGORIA_DIAG2
[nan]


In [52]:
df[df["DIAG1"]== "U099"]["DIAG1"].count()

np.int64(242)

In [13]:
    # Convert to datetime 
df['FECHA_DEF'] = pd.to_datetime(df['FECHA_DEF']) 

# Extract year 
df['YearMonth'] = df['FECHA_DEF'].dt.to_period('M') 

# Find the range of year and month 
min_year_month = df['YearMonth'].min() 
max_year_month = df['YearMonth'].max() 
print(f"Range of year and month: {min_year_month} - {max_year_month}")

Range of year and month: 2020-03 - 2024-11


In [14]:
print("\nBasic Statistics:")
print(df.describe())


Basic Statistics:
                AÑO                      FECHA_DEF     EDAD_TIPO  \
count  58313.000000                          58313  58313.000000   
mean    2021.042083  2021-06-24 13:41:42.213914368      1.000566   
min     2020.000000            2020-03-20 00:00:00      1.000000   
25%     2020.000000            2020-09-11 00:00:00      1.000000   
50%     2021.000000            2021-05-06 00:00:00      1.000000   
75%     2022.000000            2022-02-14 00:00:00      1.000000   
max     2024.000000            2024-11-14 00:00:00      3.000000   
std        0.930043                            NaN      0.025183   

          EDAD_CANT    COD_COMUNA  CAPITULO_DIAG2  GLOSA_CAPITULO_DIAG2  \
count  58313.000000  58313.000000             0.0                   0.0   
mean      73.844374  10225.798793             NaN                   NaN   
min        1.000000   1101.000000             NaN                   NaN   
25%       65.000000   7102.000000             NaN                   

In [15]:
print("\nMissing Values:")
print(df.isnull().sum())


Missing Values:
AÑO                              0
FECHA_DEF                        0
SEXO_NOMBRE                      0
EDAD_TIPO                        0
EDAD_CANT                        0
COD_COMUNA                       0
COMUNA                           0
NOMBRE_REGION                    0
DIAG1                            0
CAPITULO_DIAG1                   0
GLOSA_CAPITULO_DIAG1             0
CODIGO_GRUPO_DIAG1               0
GLOSA_GRUPO_DIAG1                0
CODIGO_CATEGORIA_DIAG1           0
GLOSA_CATEGORIA_DIAG1            0
CODIGO_SUBCATEGORIA_DIAG1        0
GLOSA_SUBCATEGORIA_DIAG1         0
DIAG2                        57368
CAPITULO_DIAG2               58313
GLOSA_CAPITULO_DIAG2         58313
CODIGO_GRUPO_DIAG2           58313
GLOSA_GRUPO_DIAG2            58313
CODIGO_CATEGORIA_DIAG2       58313
GLOSA_CATEGORIA_DIAG2        58313
CODIGO_SUBCATEGORIA_DIAG2    58313
GLOSA_SUBCATEGORIA_DIAG2     58313
LUGAR_DEFUNCION                  0
YearMonth                        0
dty